"""Merge markdown documentation into a Jupyter notebook as the first cell.

Inserts (or replaces) a markdown cell at the top of the notebook containing
the documentation content and a Binder badge. The cell is marked with an
HTML comment so it can be detected and updated on subsequent runs.
"""

import argparse
import json
import re
import os
from urllib.parse import quote


MARKER = "<!-- AUTOGENERATED-DOCS -->"


def build_binder_url(repo: str, branch: str, notebook_path: str) -> str:
    encoded_path = quote(notebook_path, safe="")
    return (
        f"https://mybinder.org/v2/gh/{repo}/{branch}"
        f"?labpath={encoded_path}"
    )


def resolve_image_paths(doc_text: str, doc_dir: str, repo: str, branch: str) -> str:
    """Replace relative image paths with raw GitHub URLs."""

    def replacer(match: re.Match) -> str:
        alt = match.group(1)
        rel_path = match.group(2)
        if rel_path.startswith(("http://", "https://")):
            return match.group(0)
        abs_path = os.path.normpath(os.path.join(doc_dir, rel_path))
        repo_rel = os.path.relpath(abs_path, start=".")
        encoded = quote(repo_rel, safe="/")
        url = f"https://raw.githubusercontent.com/{repo}/{branch}/{encoded}"
        return f"![{alt}]({url})"

    return re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", replacer, doc_text)


def make_docs_cell(doc_text: str, binder_url: str) -> dict:
    badge_md = (
        f"[![Binder](https://mybinder.org/badge_logo.svg)]({binder_url})"
    )
    source = f"{MARKER}\n{badge_md}\n\n{doc_text}"
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def has_docs_cell(notebook: dict) -> bool:
    if not notebook.get("cells"):
        return False
    first_source = "".join(notebook["cells"][0].get("source", []))
    return first_source.startswith(MARKER)


def merge(doc_path: str, notebook_path: str, repo: str, branch: str) -> None:
    with open(doc_path, "r", encoding="utf-8") as f:
        doc_text = f.read()

    doc_dir = os.path.dirname(doc_path)
    doc_text = resolve_image_paths(doc_text, doc_dir, repo, branch)

    binder_url = build_binder_url(repo, branch, notebook_path)
    docs_cell = make_docs_cell(doc_text, binder_url)

    with open(notebook_path, "r", encoding="utf-8") as f:
        notebook = json.load(f)

    if has_docs_cell(notebook):
        notebook["cells"][0] = docs_cell
    else:
        notebook["cells"].insert(0, docs_cell)

    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, ensure_ascii=False, indent=1)
        f.write("\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Merge markdown docs into a Jupyter notebook."
    )
    parser.add_argument("--doc", required=True, help="Path to the markdown doc file.")
    parser.add_argument("--notebook", required=True, help="Path to the notebook file.")
    parser.add_argument(
        "--repo",
        default="BAMresearch/NFDI4IngModelValidationPlatform",
        help="GitHub owner/repo.",
    )
    parser.add_argument("--branch", default="main", help="Git branch name.")
    args = parser.parse_args()
    merge(args.doc, args.notebook, args.repo, args.branch)


if __name__ == "__main__":
    main()
